### ISSUE TITLE
SQLiteKG can't be pickled for multiprocessing on MacOS ARM64

### ISSUE THREAD

**Issue by khaller93** [khaller93/sqlitekg2vec#1]
When using the SQLiteKG class with MacOS on ARM64, then pickling the instance for multiprocessing fails. This works fine on Linux AMD64/x86_64 architectures.

**Software info:**
* System Version: macOS 13.1 (22C65)
* Kernel Version: Darwin 22.2.0

**Hardware info:**
 * Model Name: MacBook Pro
 * Model Identifier: MacBookPro18,4
 * Model Number: Z15G0009JD/A
 * Chip: Apple M1 Max
 * Total Number of Cores: 10 (8 performance and 2 efficiency)
 * Memory: 64 GB
 * System Firmware Version: 8419.60.44

**Stacktrace:**

```
INFO     :: Imported KG with {entities:18726, predicates:46, statements: 61314}
INFO     :: training RDF2Vec model for KG "pokemon" with: {max_walks: 200, max_depth: 4, with_reverse: False, seed: 133, n_jobs: 10}
INFO     :: Word2Vec lifecycle event {'params': 'Word2Vec<vocab=0, vector_size=100, alpha=0.025>', 'datetime': '2022-12-27T20:50:08.003585', 'gensim': '4.3.0', 'python': '3.9.16 (main, Dec  7 2022, 10:06:04) \n[Clang 14.0.0 (clang-1400.0.29.202)]', 'platform': 'macOS-13.1-arm64-arm-64bit', 'event': 'created'}
Traceback (most recent call last):

  File "/Users/kevinhaller/Documents/University/KGRec/kgrec-train/main.py", line 23, in <module>
    app()

  File "/Users/kevinhaller/Documents/University/KGRec/kgrec-train/kgrec/cmd/train.py", line 25, in rdf2vec_cmd
    rdf2vec.train(model_kwargs=dict(epochs=epochs, walks=walks,

  File "/Users/kevinhaller/Documents/University/KGRec/kgrec-train/kgrec/embedding/embedding.py", line 50, in train
    self.model = self._perform_training(model_kwargs, training_kwargs)

  File "/Users/kevinhaller/Documents/University/KGRec/kgrec-train/kgrec/embedding/rdf2vec.py", line 74, in _perform_training
    return train(**model_kwargs)

  File "/Users/kevinhaller/Documents/University/KGRec/kgrec-train/kgrec/embedding/rdf2vec.py", line 67, in train
    embeddings, _ = transformer.fit_transform(kg, ent)

  File "/Users/kevinhaller/Documents/University/KGRec/kgrec-train/venv/lib/python3.9/site-packages/pyrdf2vec/rdf2vec.py", line 143, in fit_transform
    self.fit(self.get_walks(kg, entities), is_update)

  File "/Users/kevinhaller/Documents/University/KGRec/kgrec-train/venv/lib/python3.9/site-packages/pyrdf2vec/rdf2vec.py", line 178, in get_walks
    walks += walker.extract(kg, entities, self.verbose)

  File "/Users/kevinhaller/Documents/University/KGRec/kgrec-train/venv/lib/python3.9/site-packages/pyrdf2vec/walkers/walker.py", line 154, in extract
    with multiprocessing.Pool(process, self._init_worker, [kg]) as pool:

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)

  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

TypeError: cannot pickle 'generator' object
```

**Comment by khaller93** [comment]
The previous version of SQLite KG was very heavyweight for pickling. The most recent commit for this issue, introduces a more lightweight version of SQLite KG.
